name: Test
on: workflow_call
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      node_version: 18.4.0
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Dynamic Use
        uses: ./../dynamic-uses
        id: setup_node
        with:
          uses: "${{ 'actions/setup-node@v3' }}"
          with: '{ "node-version": "${{ env.node_version }}" }'
      - name: Validate outputs
        run: |
          expected="v${node_version}"
          actual="${{ fromJSON(steps.setup_node.outputs.outputs)['node-version'] }}"
          if [[ "$expected" != "$actual" ]]; then
            echo "::error::output mismatch! expected=$expected, actual=$actual"
            exit 1
          fi
